### ISSUE TITLE
Compiling projects with GCC 12.1 UCRT is painfully slow

### ISSUE THREAD

**Issue by Panjaksli** [brechtsanders/winlibs_mingw#107] opened 2022-06-27 11:59 UTC
(Latest build)
MSVCRT works as expected.

**Comment by brechtsanders** [comment] 2022-06-27 12:17
Do you have this on more than one system?

Do you know how to reproduce this so I can test for myself?

**Comment by Panjaksli** [comment] 2022-06-27 18:38
I only have laptop, so there is that :D 

I mostly noticed this with cmake when compiling targets with many (5+) header files containing classes/inline functions.

MS defender, works the same with it disabled.

Also by painfully slow, I mean 20s with UCRT instead of 5 with MSVCRT.

**Comment by brechtsanders** [comment] 2022-06-27 20:46
I can't reproduce your issue.
Are there any other differences between your UCRT and MSVCRT setup?
Are you using command line (Command Prompt, PowerShell, MSYS), an IDE, or some kind of build system (make, cmake, ninja, ...)?

**Comment by Phantom-Trigger** [comment] 2022-09-03 14:53
Hi, maybe not the accurate information, but I have the same bad compiling performance.
What's different is that both my UCRT and MSVCRT compile slowsy compared with gcc11.2.0. It's possible that this isn't a bug but the gcc's feature? The problem might be related to the headers.

I'm using the VSCode extension [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner), as far as I know, it simply runs the two command lines. For example:
compiled with gcc12.2.0
![12 2 iostream](https://user-images.githubusercontent.com/52826887/188275328-76535a54-e791-4b37-92c4-d365768938f8.PNG)
compiled with gcc11.2.0
![11 2 iostream](https://user-images.githubusercontent.com/52826887/188275762-5ac37572-2fb9-4314-b770-61cdb147c5f9.PNG)

And it's more painful when using `bits/stdc++.h`
compiled with gcc12.2.0
![12 2 bits](https://user-images.githubusercontent.com/52826887/188275821-08924986-f7fa-4de1-9083-b27e6423f774.PNG)

compiled with gcc11.2.0
![11 2 iostream](https://user-images.githubusercontent.com/52826887/188275888-074a377a-b194-41bc-bc5e-b037f0745fd1.PNG)
(My computer is a bit out of date and slow...)

As is seen, 12.2.0 compiles approximately 2x slower then 11.2.0, and when tested on Command Prompt and PowerShell, the result is the same.

Could someone tell me why the compiling is so slow? Thanks!

**Comment by brechtsanders** [comment] 2022-09-04 07:59
Since GCC 12 there is issue https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105858 which breaks precompiled headers and which for now requires GCC12 to be built without precompiled headers.

**Comment by Phantom-Trigger** [comment] 2022-09-04 13:41
Ah, thanks for replying! Maybe that's the reason.

**Comment by xtemp09** [comment] 2022-10-06 05:46
I noticed that the GCC developers have no interest in fixing bugs on Windows platform. They don't even consider patches sent. clang/LLVM developers show fundamental difference.

Perhaps, migration to clang/LLVM will relieve one's migraine.

**Comment by brechtsanders** [comment] 2022-10-06 06:39
I too have logged issues with GCC that barely got any response. Though some of them were resolved in the end.

LLVM/CLang is a different track, but it's not always an exact drop-in replacement for GCC.

But at least with LLVM/CLang Windows on ARM is supported, while GCC doesn't even look like it's working on that either.

**Comment by rockcavera** [comment] 2022-11-27 08:04
I use C compiler as a means to compile the C code generated by Nim. Since the 12.x.x releases of gcc, I have noticed a huge slowdown compared to the 11.x.x version. With gcc 11.3.0 Nim bootstrap took 3min05s. Already with gcc 12.2.0 it is taking 8min24s. I'm using msvcrt.

**Comment by brechtsanders** [comment] 2022-11-27 21:23
For speed testing purposes I have just made this release (it reverts binutils back to the previous version):
https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.1-snapshot20221126-10.0.0-msvcrt-r1

Can you try if this version works faster for you?

**Comment by sisyphus** [comment] 2022-11-27 23:05
> Can you try if this version works faster for you?

I reported a similar issue in #114 - which I subsequently closed because I'm not sure that it's a bug report that should have been filed on this forum.

As regards that slowness, I can report that this snapshot makes no appreciable difference at all.

However, @brechtsanders, I do thank you for going to the trouble of providing this snapshot.
I take it that, as regards my issue with 12.2.0, I can now rule out binutils as being the culprit.

Cheers,
Rob

**Comment by rockcavera** [comment] 2022-11-28 14:12
> For speed testing purposes I have just made this release (it reverts binutils back to the previous version): https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.1-snapshot20221126-10.0.0-msvcrt-r1
> 
> Can you try if this version works faster for you?

I tested and got this: 8min44s

**Comment by brechtsanders** [comment] 2022-11-28 20:45
I was able to build the version with precompiled headers enabled. Can you compare speed again?
https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.1-snapshot20221126-10.0.0-msvcrt-r2

**Comment by rockcavera** [comment] 2022-11-29 01:28
> I was able to build the version with precompiled headers enabled. Can you compare speed again? https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.1-snapshot20221126-10.0.0-msvcrt-r2

This new release took 8min29s

I have a table here comparing build times on Nim bootstrap, all using the same conditions. Perhaps by looking at your best performing builds you can determine what else it might be.
```
Compiler                                                          Build Time
winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64msvcrt-10.0.0-r2     00:08:24
winlibs-x86_64-posix-seh-gcc-11.3.0-mingw-w64msvcrt-10.0.0-r3     00:03:05
winlibs-x86_64-posix-seh-gcc-10.4.0-mingw-w64msvcrt-10.0.0-r1     00:07:39
winlibs-x86_64-posix-seh-gcc-9.5.0-mingw-w64msvcrt-10.0.0-r1      00:05:19
winlibs-x86_64-posix-seh-gcc-8.5.0-mingw-w64-9.0.0-r1             00:03:02
winlibs-x86_64-posix-seh-gcc-7.5.0-mingw-w64-7.0.0-r1             00:02:34
mingw-builds-x86_64-6.4.0-release-posix-seh-rt_v5-rev0            00:02:31
mingw-builds-x86_64-5.4.0-release-posix-seh-rt_v5-rev0            00:02:27
mingw-builds-x86_64-4.9.4-release-posix-seh-rt_v5-rev0            00:02:32
mingw-builds-x86_64-4.8.1-release-posix-seh-rt_v3-rev2            00:02:31
tdm64-gcc-10.3.0-2                                                00:03:24
clang-llvm-mingw-20220906-msvcrt-x86_64                           00:02:15
clang-15.0.5-posix-x86_64-pc-windows-msvc                         00:02:12
```

**Comment by sisyphus** [comment] 2022-11-30 04:00
That build by niXman of 12.2.0 (x86_64-12.2.0-release-posix-seh-rt_v10-rev1) also eradicates the slowness I reported in #114.
@brechtsanders, are you able to pinpoint the difference that accounts for this ?

Cheers,
Rob

**Comment by brechtsanders** [comment] 2022-11-30 21:59
A good next step would be to compare outputs of `gcc -v` too find out where the difference lies.

**Comment by rockcavera** [comment] 2022-12-08 04:14
> A good next step would be to compare outputs of `gcc -v` to find out where the difference lies.

I took a look and there are several differences, but for those who do not compile gcc, it is difficult to know what could be causing this slowdown in your release.

**Comment by brechtsanders** [comment] 2022-12-30 14:15
I have tried to patch the PCH issue according to MSYS2's patches.
Can you please check if the [new release](https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.2.0-15.0.6-10.0.0-msvcrt-r3) fixes any PCH and/or C++ compilation speed issues?

**Comment by rockcavera** [comment] 2022-12-30 16:27
@brechtsanders unfortunately it didn't solve the speed problem.

**Comment by term-est** [comment] 2023-01-18 07:14
12.2 feels a lot faster, and it seems like PCH is working too

Thank you for the release 🍓

**Comment by brechtsanders** [comment] 2023-01-18 19:11
@term-est Are you specifically referring to yesterday's build?

I also had the impression it was working smoother.
I have a feeling things got slower since [this issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105506), and yesterday's build finally had it patched.

But that's just a gut feeling, maybe other things were at play too.

**Comment by rockcavera** [comment] 2023-01-19 15:14
> @term-est Are you specifically referring to yesterday's build?

I downloaded and tested release 4, but the compile time remains the same. That is, it remains 2.5x slower than the one distributed by niXman.

**Comment by rockcavera** [comment] 2024-01-01 17:50
@brechtsanders  I recently tested `gcc version 13.2.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders, r4)` and it seems that the slowness problem has been resolved. I verified that you now use the `-march=nocona` switch. Was that it?

**Comment by brechtsanders** [comment] 2024-01-01 23:00
I'm not sure what caused it.
I keep improving the build process with each version, but also each version uses the latest version of all dependencies, so the issue may have been resolved in one of those.
I'm glad it's resolved now.

**Closed by brechtsanders** 2024-01-01 23:00 UTC
