### ISSUE TITLE
ccache 4.9 Error

### ISSUE THREAD

**Issue by CyberRSR** [brechtsanders/winlibs_mingw#185] opened 2024-03-04 16:01 UTC
call: ` ccache --version`
out: ` terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence`
Win10
GCC 13.2.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 17.0.6 + MinGW-w64 11.0.1 (MSVCRT) - release 5   (LATEST) - Win64

**Comment by brechtsanders** [comment] 2024-03-04 19:07
I can't reproduce that.
Are you sure you weren't calling some other `ccache.exe` somewhere else in your `PATH`?
Which shell were you running that from?
Can you try specifying the complete absolute path to `ccache.exe` ?

**Comment by CyberRSR** [comment] 2024-03-04 19:14
> I can't reproduce that. Are you sure you weren't calling some other `ccache.exe` somewhere else in your `PATH`? Which shell were you running that from? Can you try specifying the complete absolute path to `ccache.exe` ?

Yes.
`c:\MinGW\bin>C:\MinGW\bin\ccache --version`
`terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Illegal byte sequence`

**Comment by brechtsanders** [comment] 2024-03-04 19:25
Apparently you get a filesystem error.
Is your C: drive formatted in NTFS, and does it have enough disk space available?
Is your `TEMP` environment variable pointing to an existing location (without any special characters) where you have write access?
Are there any locations on your `PATH` environment variable with special characters (spaces, non-ASCII characters)?
What if you do the same thing on a different drive?

I will close this ticket as it seems to be an issue with ccache itself, and they already have a ticket for it:
https://github.com/ccache/ccache/issues/1409

**Closed as completed by brechtsanders** 2024-03-04 19:25 UTC
