### ISSUE TITLE
Windows antivirus flags dll as trojan

### ISSUE THREAD

**Issue by speedy-lex** [brechtsanders/winlibs_mingw#213] opened 2024-05-19 09:07 UTC
When I install winlibs-x86_64-posix-seh-gcc-14.1.0-llvm-18.1.5-mingw-w64ucrt-11.0.1-r1.zip from the latest release (2 weeks ago) and extract it, windows defender detects "Trojan:Win32/cerber" in the file .\bin\libLLVMX86Desc.dll and then clang and clang++ both say that they are missing the dll

**Comment by brechtsanders** [comment] 2024-05-19 09:26
Duplicate of #199

**Closed as completed by brechtsanders** 2024-05-19 09:26 UTC
