### ISSUE TITLE
Windows 11 flags latest WinLibs as carrying trojan viruses

### ISSUE THREAD

**Issue by GeneGeneGitHub** [brechtsanders/winlibs_mingw#218] opened 2024-06-05 22:16 UTC
https://winlibs.com/

GCC 14.1.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 18.1.5 + MinGW-w64 11.0.1 (UCRT) - release 1   (LATEST)

Both the .7z and .zip files were flagged and deleted by Windows Defender.

The .7z file contains Trojan:Win32/Vigorf.A
The .zip file contains Trojan:Script/Phonzy.A!m!

**Comment by Alcaro** [comment] 2024-06-05 22:18
Another dupe of #199? With this many reports and VirusTotal complaints, I'm starting to suspect there is something bad floating around.

No clue where it'd come from, though. Or why it's only in the LLVM files.

**Closed** 2024-06-06 05:59 UTC

**Comment by GeneGeneGitHub** [comment] 2024-06-06 06:00
Closed with no resolution?

**Comment by brechtsanders** [comment] 2024-06-06 07:15
Duplicate of #199
